[workspace]
members = [
  "oracle",
  "runtime",
  "runtime/client",
  "vault",
  "bitcoin",
  "faucet",
  "service",
  "cli/explore",
  "cli/redeem",
  "cli/burn",
  "cli/transfer",
  "cli/issue",
  "cli/issue_request",
  "cli/issue_pay",
  "cli/common"
]
