[package]
name = "runtime"
version = "1.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
testing-utils = [
    "tempdir",
    "interbtc",
    "rand",
    "subxt-client",
]
parachain-metadata-interlay = []
parachain-metadata-kintsugi = []
parachain-metadata-testnet = []
standalone-metadata = []

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
# start of CLI added RPC functions
#codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
# end of CLI added RPC functions
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.71"
tokio = { version = "1.0", features = ["full"] }
backoff = { version = "0.3.0", features = ["tokio"] }
futures = "0.3.5"
clap = "3.1"
log = "0.4.0"
url = "2"
cfg-if = "1.0"
prometheus = { version = "0.12.0", features = ["process"] }
# start of CLI added RPC functions
scale-info = { version = "2.0.0", default-features = false, features = ["derive"] }
# end of CLI added RPC functions

# Substrate dependencies
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.18" }

# Subxt dependencies
# https://github.com/interlay/subxt/tree/polkadot-v0.9.18
subxt = { package = "subxt", git = "https://github.com/interlay/subxt", rev = "344e44c3729adcb945b937d6703212e7ae41da50" }
subxt-client = { package = "subxt-client", path = "./client", optional = true }

jsonrpsee = { version = "0.10.1", features = ["macros", "jsonrpsee-types", "client", "jsonrpsee-ws-client", "jsonrpsee-client-transport"] }

# Polkadot dependencies
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.18" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.18" }

bitcoin = { path = "../bitcoin"}

# Dependencies for the testing utils for integration tests
tempdir = { version = "0.3.7", optional = true }
interbtc = { package = "interbtc-standalone", git = "https://github.com/interlay/interbtc", rev = "f1ed5205c29934170b0674e6b60a847028b9735e", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.primitives]
git = "https://github.com/interlay/interbtc"
rev = "f1ed5205c29934170b0674e6b60a847028b9735e"
package = "interbtc-primitives"

[dependencies.module-bitcoin]
git = "https://github.com/interlay/interbtc"
rev = "f1ed5205c29934170b0674e6b60a847028b9735e"
package = "bitcoin"

[dependencies.module-btc-relay]
git = "https://github.com/interlay/interbtc"
rev = "f1ed5205c29934170b0674e6b60a847028b9735e"
package = "btc-relay"

[dependencies.module-oracle-rpc-runtime-api]
git = "https://github.com/interlay/interbtc"
rev = "f1ed5205c29934170b0674e6b60a847028b9735e"
package = "module-oracle-rpc-runtime-api"

[dev-dependencies]
runtime = { path = ".", features = ["testing-utils"] }
tempdir = "0.3.7"
env_logger = "0.8.3"