# Gmail configuration template
global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to:
    from:
    smarthost: smtp.gmail.com:587
    auth_username:
    auth_identity:
    auth_password: 
    send_resolved: true
