name: Continuous integration

permissions:
  contents: read

on: [pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: [self-hosted, linux]
    services:
      bitcoind:
        image: docker.io/interlayhq/bitcoin-core:22.0
        ports:
          - 18443:18443

    strategy:
      matrix:
        metadata:
          - parachain-metadata-interlay
          - parachain-metadata-kintsugi
          - parachain-metadata-interlay-testnet
          - parachain-metadata-kintsugi-testnet

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Install System Dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev git clang curl libc6-dev
      - name: Set variables
        run: |
            echo "TOOLCHAIN=$(rustup show active-toolchain | cut -d " " -f1)" >> $GITHUB_ENV
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          override: true
          components: rustfmt
      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - run: rustup component add clippy
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release --workspace --features ${{ matrix.metadata }}
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release --workspace --features ${{ matrix.metadata }}
      - name: test
        if: matrix.metadata == 'parachain-metadata-kintsugi-testnet'
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: info,regalloc=warn
          BITCOIN_RPC_URL: http://127.0.0.1:18443
          BITCOIN_RPC_USER: user
          BITCOIN_RPC_PASS: pass
        with:
          command: test
          args: --release --workspace --features ${{ matrix.metadata }} --features uses-bitcoind
      - name: upload artifacts - vault
        uses: actions/upload-artifact@v2
        with:
          name: vault-${{ matrix.metadata }}-${{ github.sha }}
          path: target/release/vault
          retention-days: 10
      - name: upload artifacts - oracle
        uses: actions/upload-artifact@v2
        with:
          name: oracle-${{ matrix.metadata }}-${{ github.sha }}
          path: target/release/oracle
          retention-days: 10
      - name: upload artifacts - faucet
        uses: actions/upload-artifact@v2
        with:
          name: faucet-${{ matrix.metadata }}-${{ github.sha }}
          path: target/release/faucet
          retention-days: 10
      - name: upload artifacts - runner
        if: matrix.metadata == 'parachain-metadata-kintsugi-testnet'
        uses: actions/upload-artifact@v2
        with:
          name: runner-${{ github.sha }}
          path: target/release/runner
          retention-days: 10

  build_docker:
    if: github.ref_type == 'tag' || contains(fromJson('["master", "dev", "gha-release"]'), github.ref_name)
    needs: [test]
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        client: ["oracle", "vault", "faucet"]
        metadata:
          - parachain-metadata-interlay
          - parachain-metadata-kintsugi
          - parachain-metadata-interlay-testnet
          - parachain-metadata-kintsugi-testnet
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          TS=$(date +%s)
          echo ::set-output name=branch_name::$(echo ${GITHUB_REF##*/})
          echo ::set-output name=tag::${{ matrix.client }}-${{ matrix.metadata }}-${TAG}
          echo ::set-output name=ts::${TS}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.client }}-${{ matrix.metadata }}
          path: artifacts/

      - run: |
          find ./artifacts
          mkdir -p ./target/release/
          mv ./artifacts/${{ matrix.client }} ./target/release/${{ matrix.client }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/interlayhq/interbtc-clients
          tags: |
            type=sha,prefix=${{ steps.prep.outputs.branch_name }}-,suffix=-${{ steps.prep.outputs.ts }}
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          context: .
          file: .deploy/Dockerfile
          build-args: |
            BINARY=${{ matrix.client }}
            PROFILE=release

  publish-draft-release:
    if: github.ref_type == 'tag'
    runs-on: [self-hosted, linux]
    needs: [test]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - run: |
          find ./artifacts
          find . -type f -exec sha256sum {} \; > ./artifacts/sha256sums.txt
          git-chglog --output CHANGELOG.md $GITHUB_REF_NAME
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          draft: true
          files: |
            artifacts/*/*